version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: intro-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

#  intro-spring-app:
#    container_name: intro-spring-app
#    build:
#      dockerfile: ./Dockerfile
#      args:
#        profile: local
#    ports:
#      - 8080:8080
#      - 5005:5005
#    depends_on:
#      - postgres
